imports:
    - { resource: parameters.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# Doctrine Configuration
# doctrine:
#     dbal:
#         driver:   pdo_mysql
#         charset:  UTF8
#
#     orm:
#         auto_generate_proxy_classes: "%kernel.debug%"
#         naming_strategy: doctrine.orm.naming_strategy.underscore
#         auto_mapping: true


monolog:
    handlers:
        applog:
            type: stream
            path: /var/log/behat-ci.log
            level: debug
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
