#!/usr/bin/env php
<?php
set_time_limit(0);
//include composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
//import commands
use AppBundle\Commands\Help;
use AppBundle\Commands\Schedule;
use AppBundle\Commands\Trigger;
use AppBundle\Commands\Clear;
use AppBundle\Commands\Test;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
//Register new command
$application->add(new Help());
$application->add(new Schedule());
$application->add(new Trigger());
$application->add(new Clear());
$application->add(new Test());
$application->run($input);
